### ISSUE TITLE
<menu_vector> tag requires viewportWidth > 0

### ISSUE THREAD

**Issue by RadicalMonkey** [wnafee/vector-compat#10]
Hi,

I've attempted to implement your library and it works great on Android 5.X.X and above however Im getting some issues on devices running 4.X.X. Below is a partial of my xml for the vector drawable as the path data is quite long. Ive also got both `app:vc_pathData` and `app:vc_fillColor` on every path tag as well as the normal `android:` ones

``` xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:width="85dp"
        android:height="36dp"
        android:viewportWidth="85"
        android:viewportHeight="36"

        app:vc_viewportWidth="85"
        app:vc_viewportHeight="36">
```

Im applying this to the MorphButton in xml in my layout however I get the error in the title when I run on devices 4.X.X.

What am I missing?

**Comment by wnafee** [comment]
what version of `buildToolsVersion` are you using?

**Comment by RadicalMonkey** [comment]
Doh! That was the problem! Got the hard part right but glossed over that little detail. Thanks.

On a side note, I couldn't find it in the docs but do I have to use the `MorphButton` to us this in xml?

**Comment by wnafee** [comment]
`MorphButton` will automatically inflate your vector from xml into the view. However, you can manually inflate in Java using `ResourcesCompat.getDrawable(...)` passing your vector xml resId. That should return a `VectorDrawable` for you also.

**Comment by RadicalMonkey** [comment]
Thanks, that's very helpful
