### ISSUE TITLE
Backport to API 8

### ISSUE THREAD

**Issue by Tibolte** [wnafee/vector-compat#11]
Is it planned for this project? Or do you want to keep it as minSdk 14?

**Comment by janheinrichmerker** [comment]
Android docs recommend you to not develop for devices lower than API14 anymore. API14+ is actually 94.1% of all Android devices.

**Comment by Tibolte** [comment]
API14 should be the way to go definitely, I'm still having clients asking for backport 8. I'm closing this issue.
