### ISSUE TITLE
Question About Installing The Library

### ISSUE THREAD

**Issue by averydelmiller** [wnafee/vector-compat#13]
Hey! I'm new to support libraries to please bear with me!
I'm confused about how one installs the library:
-Should I download the .pom or the .aar file?
-Where should I put the file?
Thanks for your help!
(I'm using Android Studio and the Android SDK.)

**Comment by janheinrichmerker** [comment]
You should add it to your gradle dependencies as described in the README.

**Comment by wnafee** [comment]
As per the README, add the following dependency in your project `build.gradle` file:

``` groovy
dependencies {
    compile 'com.wnafee:vector-compat:1.0.5'
}
```
