### ISSUE TITLE
Button with AnimatedVectorDrawable compat doesn't show background 

### ISSUE THREAD

**Issue by olegosipenko** [wnafee/vector-compat#14]
Maybe I've missed something, but I stumbled a little.
I have an xml layout with button, in Java code I'm using 

```
Drawable avd = ResourcesCompat.getDrawable(getActivity(), R.drawable.btn_signin_avd);
mBtnSignin.setBackground(avd);
```

Animations working good, but when not animating my button is transparent, though on Lollipop devices it shows background descrided in the `<vector><path>pathData</path></vector>` section. And I duplicate `pathData` attribute value with `app:vc_pathData`.

**Comment by wnafee** [comment]
`mBtnSignin` is that a normal `Button`?
I can't tell from your code what would cause your AVD to animate to begin with.
Please share more info

**Comment by olegosipenko** [comment]
Yeah, it's normal button
**btn_signin_avd**

```
 <?xml version="1.0" encoding="utf-8"?>
 <animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
     android:drawable="@drawable/btn_signin_vd">

 <target
     android:animation="@anim/btn_signin_morph"
     android:name="btn_signin"/>

 </animated-vector>
```

**btn_signin_vd**

```
<vector
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
android:width="290dp"
android:height="48dp"
android:viewportHeight="48"
app:vc_viewportHeight="48"
app:vc_viewportWidth="290"
android:viewportWidth="290">

<path
    android:name="btn_signin"
    android:fillColor="@color/btn_signin"
    app:vc_fillColor="@color/btn_signin"
    android:pathData="@string/btn_signin_from"
    app:vc_pathData="@string/btn_signin_from"
    />

</vector>
```

 **button in xml**

```
<Button
            android:id="@+id/btn_signin"
            android:layout_width="@dimen/btn_signin_width"
            android:layout_height="@dimen/btn_signin_height"
            tools:background="@drawable/btn_signin_avd"
            android:text="@string/login"
            android:textAppearance="?android:textAppearanceButton"
            android:textColor="@android:color/white"/>
```

**Comment by wnafee** [comment]
I see nothing in the code that would cause your AVD to begin animating.

**Comment by olegosipenko** [comment]
I call this line `((Animatable) mBtnSignin.getBackground()).start();` in the OnClickListener. Though animation runs successfully, the problem that it doesn't show background in the normal state

**Comment by wnafee** [comment]
So to understand your question, you're saying the AVD fillcolor appears transparent unless it's animating?

**Comment by olegosipenko** [comment]
exactly

**Comment by wnafee** [comment]
Not sure how this can be.
Can you try using `MorphButton` instead of a normal `Button` and set its `android:background` to be transparent and then set its `app:vc_startDrawable` to be your `btn_signin_avd`.

A `MorphButton` will automatically take care of triggering the animation on the AVD when clicked so you can remove your `OnClickListener` code. It will also automatically inflate the AVD and set it to your button foreground image, so again remove this from your code --> `mBtnSignin.setBackground(avd);`

**Comment by olegosipenko** [comment]
Better to stay with existing code
uploaded video https://youtu.be/KUCxidmlWaY

**Comment by olegosipenko** [comment]
Strange, just tried your lib at home on another PC and another project and it works well. Will try to find the difference on Monday

**Comment by olegosipenko** [comment]
The problem was in wrong build tools version. Changing to `22.0.1` fixed it
