### ISSUE TITLE
Crash on KitKat

### ISSUE THREAD

**Issue by Nairou** [wnafee/vector-compat#15]
Is there some trick to getting a project to use vector-compat, beyond adding it to the gradle dependency list? When I try to display a vector drawable (not animated, not MorphButton), it crashes when run under KitKat (API 19).

The error is:

```
org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
```

The stack trace shows no sign of com.wnafee, so I can't tell if it is actually functioning.

For reference, here is the drawable I'm trying to display (as a Button background):

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:width="24dp"
        android:height="24dp"
        app:vc_viewportHeight="24"
        app:vc_viewportWidth="24"
        android:viewportHeight="24"
        android:viewportWidth="24">
    <path
        app:vc_fillColor="#FFFFFF"
        app:vc_pathData="@string/vector_qrcode"
        android:fillColor="#FFFFFF"
        android:pathData="@string/vector_qrcode"/>
</vector>
```

**Comment by wnafee** [comment]
what version of `buildToolsVersion` are you using?

**Comment by Nairou** [comment]
Same as in your readme:

```
buildToolsVersion "22.0.1"
```

**Comment by wnafee** [comment]
It seems to me that you're using Kitkat `Resources` to inflate the drawable instead of the `ResourcesCompat` that I've provided. 
Can you show me what code you're using to inflate the drawable?

**Comment by Nairou** [comment]
That was actually something I didn't understand. I'm very new to Android development. All I've done is added the vector drawable in XML and referenced that. I have not manually called any code for inflating it, I assumed that was automatic if you didn't need to control it from code.

Do I need to be doing this from code to get it to work?

**Comment by wnafee** [comment]
Under normal circumstances what you did would be fine. However, since for this type of drawable we're trying to force the `vector-compat` library to do the inflation rather than the normal SDK's `Resources` class, things need to happen slightly differently.

If you're not using `MorphButton` then you cannot assign the drawable to be used in XML as part of another view (`MorphButton` would do that automatically for you). In your case you would have to do it in java code. It would look something like this:

``` java
//Inflate drawable using ResourcesCompat provided by the library
Drawable myVectorDrawable = ResourcesCompat.getDrawable(context, R.drawable.my_vector_drawable);
//inflate your view as normal
View myView = findViewById(R.id.myView);
//set your vector drawable to your view's background as normal
myView.setBackground(myVectorDrawable);
```

make sure to  remove referencing the vector drawable in your view's xml

**Comment by Nairou** [comment]
Ahh okay that makes sense now, I'll give it a shot. Thanks!

**Comment by sigma1326** [comment]
i use vectorDrawables for LikeButton in my layouts and in api19, app crashes again.
even with vectorDrawables.useSupportLibrary = true
does anyone know to solve this?
