### ISSUE TITLE
Using vector-compat library along with ViewPagerIndicator library produces gradle errors

### ISSUE THREAD

**Issue by Lukafin** [wnafee/vector-compat#6]
Hi.

I am using your lib and also ViewPagerIndicator (com.viewpagerindicator:library:2.4.1@aar).
Gradle gets me these errors:
Error:(1) Attribute "strokeWidth" has already been defined
Error:(1) Attribute "strokeWidth" has already been defined
Error:(1) Attribute "fillColor" has already been defined

I think it is something with naming convention (i found similiar problem here for some other lib, maybe it can help you: https://bitbucket.org/mobigosoft/graphlib/issue/1/error-attribute-strokecolor-has-already)

**Comment by Lukafin** [comment]
It also conflicts  (same 3 errors) with google play services, specifically with com.google.android.gms:play-services-wallet:7.0.0

**Comment by wnafee** [comment]
Can you tell me which version of `buildToolsVersion` are you using in your gradle file?

**Comment by Lukafin** [comment]
I am using 22.0.1.

**Comment by inktomi** [comment]
I had the same problem. 22.0.1 and latest play services+view pager indicator. Good to see you know about it!

**Comment by wnafee** [comment]
It seems I'll have to refactor all the attribute names to avoid conflict. I'll prefix them with "vc_"
Hopefully will get this done very soon.

**Comment by wnafee** [comment]
The latest commit 92ac89a87f6b0a20a8a790a865df76d5140da7c5 resolves this issue
Attributes are now prefixed with `vc_`
The good news is, if the attribute is already part of the `android:` namespace on v14+ you don't need to include it your xml anymore. This greatly reduces the amount of duplicate attributes in xml files :+1:  
Thanks to @ahmedre for the help refactoring

**Comment by Lukafin** [comment]
My gradle build process still doesn't finish without errors. Do i need to change something?
I have this line: compile 'com.wnafee:vector-compat:1.0.2'

**Comment by ahmedre** [comment]
@Lukafin that's because @wnafee hasn't pushed a new version yet - `1.0.2` doesn't do the renaming. until he pushes the new version, you could probably use the code directly instead in a library project.

**Comment by Lukafin** [comment]
Ok, thanks for the info.

**Comment by wnafee** [comment]
@Lukafin once you confirm the issue is not resolved on your end I'll start releasing to maven central with release version 1.0.3

**Comment by Lukafin** [comment]
Hi can i check if everything is ok in the latest commit without using gradle? Just copy files from .src folder to my project?

**Comment by wnafee** [comment]
If you do that you'll also have to copy the items in the `res/values` folder as well.

**Comment by Lukafin** [comment]
I copied src folder and res/values and now it compiles correctly. Now i have problem setting VectorDrawable as button's background.
My code:
  VectorDrawable vd=VectorDrawable.getDrawable(getActivity(), R.drawable.referral_part_1);
   button.setBackground(vd);

When i debug it, variable vd is not null. But when setting to button, nothing is displayed.

**Comment by wnafee** [comment]
you should call this instead:
`button.setStartDrawable(vd);`
Alternatively you can simply pass the resource id by calling this:
`button.setStartDrawable(R.drawable.referral_part_1);`

**Comment by Lukafin** [comment]
So i cant use VectorDrawble with standard Android SDK UI elements like Button, ImageView,...?
I need to use MorphButton?

**Comment by wnafee** [comment]
(Sorry, in my previous response I thought your button was a `MorphButton`)
To answer your last question, you should be able to fine since `VectorDrawable` extends from `Drawable` so you can set it as the background of any view once you inflate it.

**Comment by wnafee** [comment]
I've updated the `demo` to show an example of how to use `VectorDrawable` with a normal button. Please see this as an example:
https://github.com/wnafee/vector-compat/blob/master/demo/src/main/java/com/wnafee/vector/compat/demo/MainActivity.java

**Comment by Lukafin** [comment]
Thanks for all of your help! Everything is working now. My code was correct, i had an error in my vector_drawable.xml (attributes in path were not listed twice). 

I will switch to your 1.0.3 lib when its published to maven.

**Comment by wnafee** [comment]
Hi @Lukafin you can now use version 1.0.5
Keep in mind that attribute names have changed a lot, so please be careful how you name them. I recommend going through the [README][1] to see latest tutorial and see the `demo` app for examples.

There are also a lot of new features such as: fully backwards compatible (api14+) tinting support for button background as well as foreground drawables,  ability to attach `OnStateChangedListeners` etc.

Let me know if you have any questions.

[1]: https://github.com/wnafee/vector-compat/blob/master/README.md

**Comment by Lukafin** [comment]
So far so good, thx for the update.
